package jjr.com.playandroids.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import jjr.com.playandroids.utils.litao.TreeBean;
import jjr.com.playandroids.beans.fivelistbean.SearchDetails;

import jjr.com.playandroids.dao.TreeBeanDao;
import jjr.com.playandroids.dao.SearchDetailsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig treeBeanDaoConfig;
    private final DaoConfig searchDetailsDaoConfig;

    private final TreeBeanDao treeBeanDao;
    private final SearchDetailsDao searchDetailsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        treeBeanDaoConfig = daoConfigMap.get(TreeBeanDao.class).clone();
        treeBeanDaoConfig.initIdentityScope(type);

        searchDetailsDaoConfig = daoConfigMap.get(SearchDetailsDao.class).clone();
        searchDetailsDaoConfig.initIdentityScope(type);

        treeBeanDao = new TreeBeanDao(treeBeanDaoConfig, this);
        searchDetailsDao = new SearchDetailsDao(searchDetailsDaoConfig, this);

        registerDao(TreeBean.class, treeBeanDao);
        registerDao(SearchDetails.class, searchDetailsDao);
    }
    
    public void clear() {
        treeBeanDaoConfig.clearIdentityScope();
        searchDetailsDaoConfig.clearIdentityScope();
    }

    public TreeBeanDao getTreeBeanDao() {
        return treeBeanDao;
    }

    public SearchDetailsDao getSearchDetailsDao() {
        return searchDetailsDao;
    }

}
