package jjr.com.playandroids.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import jjr.com.playandroids.beans.fivelistbean.SearchDetails;
import jjr.com.playandroids.utils.litao.CollectUtils;
import jjr.com.playandroids.utils.litao.TreeBean;

import jjr.com.playandroids.dao.SearchDetailsDao;
import jjr.com.playandroids.dao.CollectUtilsDao;
import jjr.com.playandroids.dao.TreeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchDetailsDaoConfig;
    private final DaoConfig collectUtilsDaoConfig;
    private final DaoConfig treeBeanDaoConfig;

    private final SearchDetailsDao searchDetailsDao;
    private final CollectUtilsDao collectUtilsDao;
    private final TreeBeanDao treeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchDetailsDaoConfig = daoConfigMap.get(SearchDetailsDao.class).clone();
        searchDetailsDaoConfig.initIdentityScope(type);

        collectUtilsDaoConfig = daoConfigMap.get(CollectUtilsDao.class).clone();
        collectUtilsDaoConfig.initIdentityScope(type);

        treeBeanDaoConfig = daoConfigMap.get(TreeBeanDao.class).clone();
        treeBeanDaoConfig.initIdentityScope(type);

        searchDetailsDao = new SearchDetailsDao(searchDetailsDaoConfig, this);
        collectUtilsDao = new CollectUtilsDao(collectUtilsDaoConfig, this);
        treeBeanDao = new TreeBeanDao(treeBeanDaoConfig, this);

        registerDao(SearchDetails.class, searchDetailsDao);
        registerDao(CollectUtils.class, collectUtilsDao);
        registerDao(TreeBean.class, treeBeanDao);
    }
    
    public void clear() {
        searchDetailsDaoConfig.clearIdentityScope();
        collectUtilsDaoConfig.clearIdentityScope();
        treeBeanDaoConfig.clearIdentityScope();
    }

    public SearchDetailsDao getSearchDetailsDao() {
        return searchDetailsDao;
    }

    public CollectUtilsDao getCollectUtilsDao() {
        return collectUtilsDao;
    }

    public TreeBeanDao getTreeBeanDao() {
        return treeBeanDao;
    }

}
